---
- name: set hostname
  when: ansible_facts['os_family']|lower == 'debian'
  hostname:
    name: "{{ inventory_hostname }}"
- name: set timezone
  timezone:
    name: '{{ timezone }}'
- name: force bash to store history
  copy:
    dest: /etc/profile.d/bash_force_history_write.sh
    content: |
      #!/bin/sh
      shopt -s histappend
      PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
    mode: '0755'
- name: enable universe repository
  tags:
    - apt
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: universe
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"
  when: >
    ansible_distribution_version > '16.04'
- name: install apt packages
  tags:
    - apt
  when: ansible_facts['os_family']|lower == 'debian'
  apt: 
    name: "{{ apt_packages }}"
    state: latest
    update_cache: yes



- name: Install Pip.
  become: true
  apt:
    name: python3-pip
    state: latest
  tags: [config-docker]

- name: Install Docker Python library.
  become: true
  pip:
    name: docker
    state: latest
  tags: [config-docker]

- name: Install Docker Python library.
  become: true
  pip:
    name: jsondiff
    state: latest
  tags: [config-docker]

- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: true
  tags: [server-update]

- name: Upgrade exist packages
  become: true
  apt:
    upgrade: safe
  tags: [server-update]

